### PR TITLE
WIP - initial workings to delete multiple entries in the CMS

### PR DESCRIPTION
**Pull request by Toycel03**
This relates to https://github.com/nystudio107/craft-retour/issues/22

This is a work in progress.  I have started on the initial outline of the project with the UI complete and some of the funcitons in the backend (which need tidying up and possibly expanding upon) 

I need to complete the work on this in the coming weeks to be able to pass the selected values to the controller from the vue template.

### CODE REVIEW

**Comment by khalwat** [comment]
Seems like a valid approach -- there's also this in VueTable that you can leverage tho:

https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-11#__checkbox

Which could then be combined with a Craft-style gearbox icon to do bulk actions.

**Comment by Toycel03** [comment]
Thanks @khalwat, I've still got some work to do but that also looks like a way forward. With the table being built using Vue there is nothing on the frontend intially.

**Comment by khalwat** [comment]
I've implemented this; it'll be released as 3.1.28 shortly.

**Comment by khalwat** [comment]
Screen Shot 2019-11-11 at 4 49 21 PM

**Pull request closed without merging**
